# Generated by Django 5.0.7 on 2024-07-18 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personpage',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personpage',
            name='death_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='personpage',
            name='rank_or_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='personpage',
            name='unit_or_affiliation',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
